apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 607458533394.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
        ports:
        - containerPort: 3000

